import {C} from './config.js';
import {project,makeViewports} from './camera.js';
import {drawCharacter} from './characters.js';

export function render(ctx,width,height,state,assets,input){
  const vps=makeViewports(width,height,state);for(const vp of vps){const control=input.visuals(vp.player);ctx.save();ctx.beginPath();ctx.rect(vp.x,vp.y,vp.w,vp.h);ctx.clip();renderWorld(ctx,vp,state,assets,control);renderControls(ctx,vp,state);renderParticles(ctx,vp,state);ctx.restore();}
  if(vps.length===2){ctx.fillStyle='rgba(255,255,255,.72)';ctx.fillRect(width/2-2,0,4,height);}return vps;
}
function renderWorld(ctx,vp,state,assets,control){
  const g=ctx.createLinearGradient(0,vp.y,0,vp.h);g.addColorStop(0,C.COLORS.sky);g.addColorStop(.62,'#FFF4D7');g.addColorStop(1,'#F7CDB8');ctx.fillStyle=g;ctx.fillRect(vp.x,vp.y,vp.w,vp.h);
  ctx.fillStyle='rgba(255,255,255,.35)';for(let i=0;i<5;i++){ctx.beginPath();ctx.arc(vp.x+vp.w*(.1+i*.23),vp.h*.16+(i%2)*20,30+i*4,0,7);ctx.fill();}
  drawFloor(ctx,vp);drawTable(ctx,vp,assets);
  const cam=vp.camera,viewer=state.players[vp.player],opponent=state.players[1-vp.player];
  const op=project(vp,cam,opponent.x,.22,opponent.z);if(op){const size=Math.min(vp.h*.46,op.scale*.85);const img=assets.images[`${opponent.character}_${opponent.pose}`]||assets.images[`${opponent.character}_idle`];if(img)ctx.drawImage(img,op.sx-size/3,op.sy-size*.42,size*2/3,size);else drawCharacter(ctx,opponent.character,op.sx,op.sy,size,opponent.pose,cam.side>0);}
  const ballFar=(viewer.side<0?state.ball.z>0:state.ball.z<0);if(ballFar){drawShadow(ctx,vp,state);drawBall(ctx,vp,state,assets);}drawNet(ctx,vp,state,assets);if(!ballFar){drawShadow(ctx,vp,state);drawBall(ctx,vp,state,assets);}drawViewmodel(ctx,vp,viewer,assets,control,state);
}
function drawFloor(ctx,vp){ctx.fillStyle='#E9BBAA';ctx.beginPath();ctx.moveTo(vp.x,vp.h*.62);ctx.lineTo(vp.x+vp.w,vp.h*.62);ctx.lineTo(vp.x+vp.w,vp.h);ctx.lineTo(vp.x,vp.h);ctx.fill();ctx.strokeStyle='rgba(255,255,255,.24)';ctx.lineWidth=2;for(let i=0;i<7;i++){ctx.beginPath();ctx.moveTo(vp.x+vp.w/2,vp.h*.62);ctx.lineTo(vp.x+vp.w*i/6,vp.h);ctx.stroke();}}
function drawTable(ctx,vp,assets){const cam=vp.camera,corners=[[-C.TABLE_W/2,0,-C.TABLE_L/2],[C.TABLE_W/2,0,-C.TABLE_L/2],[C.TABLE_W/2,0,C.TABLE_L/2],[-C.TABLE_W/2,0,C.TABLE_L/2]].map(p=>project(vp,cam,...p));if(corners.some(x=>!x))return;ctx.beginPath();ctx.moveTo(corners[0].sx,corners[0].sy);for(let i=1;i<4;i++)ctx.lineTo(corners[i].sx,corners[i].sy);ctx.closePath();ctx.fillStyle=C.COLORS.table;ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=Math.max(3,vp.w*.005);ctx.stroke();ctx.strokeStyle='rgba(74,74,106,.25)';ctx.lineWidth=2;const a=project(vp,cam,0,.002,-C.TABLE_L/2),b=project(vp,cam,0,.002,C.TABLE_L/2);if(a&&b){ctx.beginPath();ctx.moveTo(a.sx,a.sy);ctx.lineTo(b.sx,b.sy);ctx.stroke();}
  for(const x of [-C.TABLE_W*.42,C.TABLE_W*.42]){const p=project(vp,cam,x,-C.TABLE_H,[ -C.TABLE_L*.38,C.TABLE_L*.38][x>0?1:0]);if(p){ctx.strokeStyle=C.COLORS.ink;ctx.lineWidth=Math.max(4,p.scale*.035);ctx.beginPath();ctx.moveTo(p.sx,p.sy-p.scale*C.TABLE_H);ctx.lineTo(p.sx,p.sy);ctx.stroke();}}
}
function drawNet(ctx,vp,state,assets){const cam=vp.camera,l=project(vp,cam,-C.TABLE_W/2-C.NET_OVERHANG,C.NET_H,0),r=project(vp,cam,C.TABLE_W/2+C.NET_OVERHANG,C.NET_H,0),lb=project(vp,cam,-C.TABLE_W/2-C.NET_OVERHANG,0,0),rb=project(vp,cam,C.TABLE_W/2+C.NET_OVERHANG,0,0);if(!l||!r||!lb||!rb)return;const wob=Math.sin(state.time*35)*state.netWobble*5;ctx.fillStyle='rgba(255,255,255,.68)';ctx.beginPath();ctx.moveTo(l.sx,l.sy+wob);ctx.lineTo(r.sx,r.sy-wob);ctx.lineTo(rb.sx,rb.sy);ctx.lineTo(lb.sx,lb.sy);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(74,74,106,.38)';ctx.lineWidth=1;for(let i=0;i<=10;i++){const t=i/10;ctx.beginPath();ctx.moveTo(lerp(l.sx,r.sx,t),lerp(l.sy+wob,r.sy-wob,t));ctx.lineTo(lerp(lb.sx,rb.sx,t),lerp(lb.sy,rb.sy,t));ctx.stroke();}for(let i=0;i<4;i++){const t=i/3;ctx.beginPath();ctx.moveTo(lerp(l.sx,lb.sx,t),lerp(l.sy+wob,lb.sy,t));ctx.lineTo(lerp(r.sx,rb.sx,t),lerp(r.sy-wob,rb.sy,t));ctx.stroke();}}
function drawShadow(ctx,vp,state){const b=state.ball,ground=Math.abs(b.x)<=C.TABLE_W/2&&Math.abs(b.z)<=C.TABLE_L/2?0:-C.TABLE_H,p=project(vp,vp.camera,b.x,ground+.004,b.z);if(!p)return;const ss=1+b.y*.6,alpha=.28/(1+b.y*1.2);ctx.fillStyle=`rgba(74,74,106,${Math.max(.04,alpha)})`;ctx.beginPath();ctx.ellipse(p.sx,p.sy,C.BALL_R*p.scale*1.2*ss,C.BALL_R*p.scale*.42*ss,0,0,7);ctx.fill();}
function drawBall(ctx,vp,state,assets){const b=state.ball;if(!b.active&&state.serveStage===0&&state.server===vp.player)return;const p=project(vp,vp.camera,b.x,b.y,b.z);if(!p)return;const r=Math.max(4,Math.min(24,C.BALL_R*p.scale));ctx.save();ctx.shadowColor='rgba(74,74,106,.25)';ctx.shadowBlur=r*.7;if(assets.images.ball)ctx.drawImage(assets.images.ball,p.sx-r,p.sy-r,r*2,r*2);else{const g=ctx.createRadialGradient(p.sx-r*.35,p.sy-r*.4,1,p.sx,p.sy,r);g.addColorStop(0,'#fff');g.addColorStop(1,'#FFE5F0');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.sx,p.sy,r,0,7);ctx.fill();}ctx.restore();}
function drawViewmodel(ctx,vp,p,assets,control,state){
  const lift=control.leftHandLift||0,leftX=vp.x+vp.w*.25,leftY=vp.y+vp.h*(.88-lift*.36),armW=Math.max(18,vp.w*.055);
  ctx.save();ctx.lineCap='round';ctx.strokeStyle='#FFD7BD';ctx.lineWidth=armW;ctx.beginPath();ctx.moveTo(vp.x+vp.w*.06,vp.y+vp.h*1.04);ctx.lineTo(leftX,leftY);ctx.stroke();ctx.fillStyle='#FFD7BD';ctx.strokeStyle=C.COLORS.ink;ctx.lineWidth=Math.max(3,armW*.16);ctx.beginPath();ctx.arc(leftX,leftY,armW*.62,0,Math.PI*2);ctx.fill();ctx.stroke();
  if(!state.ball.active&&state.serveStage===0&&state.server===vp.player){const r=Math.max(7,Math.min(15,vp.w*.023));ctx.fillStyle='#fff';ctx.shadowColor='rgba(74,74,106,.28)';ctx.shadowBlur=7;ctx.beginPath();ctx.arc(leftX,leftY-r*1.8,r,0,Math.PI*2);ctx.fill();ctx.shadowBlur=0;ctx.stroke();}ctx.restore();
  const t=1-p.swingTime/C.SWING_TIME,swing=p.swingTime>0?Math.sin(Math.min(1,Math.max(0,t))*Math.PI):0,w=vp.w*(vp.w/vp.h<.85?.52:.42),h=vp.h*(vp.w/vp.h<.85?.45:.55),x=vp.x+vp.w-w*.72+swing*w*.08,y=vp.y+vp.h-h*.67-swing*h*.11;const img=assets.images[`${p.character}_${p.swingTime>0?'arm_swing':'arm'}`];if(img){ctx.drawImage(img,x,y,w,h);return;}ctx.save();ctx.translate(x+w*.6,y+h*.65);ctx.rotate(-.55-swing*.75);ctx.lineCap='round';ctx.strokeStyle='#FFD7BD';ctx.lineWidth=Math.max(20,w*.09);ctx.beginPath();ctx.moveTo(w*.22,h*.22);ctx.lineTo(-w*.1,-h*.13);ctx.stroke();ctx.strokeStyle=C.COLORS.ink;ctx.lineWidth=Math.max(8,w*.035);ctx.beginPath();ctx.moveTo(-w*.1,-h*.13);ctx.lineTo(-w*.23,-h*.29);ctx.stroke();ctx.fillStyle='#E94B4B';ctx.strokeStyle=C.COLORS.ink;ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(-w*.29,-h*.36,w*.095,h*.13,-.55,0,7);ctx.fill();ctx.stroke();ctx.restore();
}
function renderControls(ctx,vp,state){const p=state.players[vp.player],h=project(vp,vp.camera,p.x,.10,p.z+.40*(-p.side)),r=Math.min(vp.w,vp.h)*.105;ctx.save();ctx.textAlign='center';ctx.lineWidth=4;ctx.setLineDash([8,8]);ctx.strokeStyle='rgba(255,255,255,.62)';const hx=h?clamp(h.sx,vp.x+r,vp.x+vp.w-r):vp.x+vp.w*.72,hy=h?clamp(h.sy,vp.y+r+40,vp.y+vp.h-r-28):vp.h*.7;ctx.beginPath();ctx.arc(hx,hy,r,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.fillStyle='rgba(74,74,106,.45)';ctx.font=`800 ${Math.max(13,vp.w*.025)}px sans-serif`;ctx.fillText('오른손  ↑ 톱스핀',hx,hy-r-7);ctx.fillText('↓ 백스핀',hx,hy+r+18);if(!state.ball.active&&state.server===vp.player){ctx.fillText('왼손을 위로 ↑',vp.x+vp.w*.23,vp.y+vp.h*.66);}ctx.restore();}
function renderParticles(ctx,vp,state){for(const p of state.particles){if(p.player!==vp.player&&p.screen)continue;let x,y;if(p.screen){x=vp.x+p.x*vp.w;y=p.y*vp.h;}else{const q=project(vp,vp.camera,p.x,p.y,p.z);if(!q)continue;x=q.sx;y=q.sy;}ctx.globalAlpha=Math.min(1,p.life*2);ctx.fillStyle=p.color;ctx.font=`800 ${p.size}px sans-serif`;if(p.shape==='text'||p.shape==='star')ctx.fillText(p.text||'★',x,y);else ctx.fillRect(x,y,p.size,p.size*.65);}ctx.globalAlpha=1;for(const b of state.bubbles){if(b.player!==vp.player)continue;ctx.fillStyle='#fff';ctx.strokeStyle=C.COLORS.girl;ctx.lineWidth=4;const x=vp.x+vp.w*.5,y=vp.h*.25;ctx.beginPath();ctx.roundRect(x-65,y-28,130,56,22);ctx.fill();ctx.stroke();ctx.fillStyle=C.COLORS.ink;ctx.font='800 24px sans-serif';ctx.fillText(b.text,x,y+8);}}
const lerp=(a,b,t)=>a+(b-a)*t,clamp=(v,a,b)=>Math.max(a,Math.min(b,v));
